# Generated by Django 5.1.6 on 2025-04-28 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credentials', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_count', models.PositiveIntegerField()),
                ('enrollment_year', models.PositiveIntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(default='course_images/default.png', upload_to='course_images/', verbose_name='Course Image')),
                ('category', models.CharField(choices=[('python', 'Python'), ('web-development', 'Web Development'), ('sql', 'SQL'), ('php', 'PHP')], default='python', max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.instructor')),
            ],
        ),
    ]
